from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

SCHEMA = ["user_id", "item_id", "category", "timestamp", "interaction_strength"]


def seed_everything(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    try:
        import torch

        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    except ImportError:
        pass


def validate_interactions(df: pd.DataFrame, allow_empty: bool = False) -> pd.DataFrame:
    missing = [column for column in SCHEMA if column not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    result = df[SCHEMA].copy()
    if result.empty and not allow_empty:
        raise ValueError("Interaction data is empty")
    if result[SCHEMA[:-1]].isna().any().any():
        raise ValueError("user_id, item_id, category and timestamp may not be null")
    result["user_id"] = result["user_id"].astype(str)
    result["item_id"] = result["item_id"].astype(str)
    result["category"] = result["category"].astype(str)
    result["timestamp"] = pd.to_datetime(result["timestamp"], utc=True, errors="raise")
    result["interaction_strength"] = pd.to_numeric(
        result["interaction_strength"], errors="raise"
    ).astype("float32")
    if (result["interaction_strength"] <= 0).any():
        raise ValueError("interaction_strength must be positive")
    return result.sort_values(["user_id", "timestamp", "item_id"]).reset_index(drop=True)


def read_interactions(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Interaction file does not exist: {path}")
    if path.suffix.lower() == ".parquet":
        df = pd.read_parquet(path)
    elif path.suffix.lower() in {".csv", ".gz"}:
        df = pd.read_csv(path)
    else:
        raise ValueError("Supported input formats are .csv, .csv.gz and .parquet")
    return validate_interactions(df)


def write_interactions(df: pd.DataFrame, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    clean = validate_interactions(df)
    if path.suffix.lower() == ".parquet":
        clean.to_parquet(path, index=False)
    elif path.suffix.lower() in {".csv", ".gz"}:
        clean.to_csv(path, index=False)
    else:
        raise ValueError("Output must end in .csv, .csv.gz or .parquet")
    return path


def dump_json(payload: dict[str, Any], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


SYNTHETIC_CAUTION = (
    "Data was generated by a controlled simulation. Metrics measure whether the "
    "model recovers patterns injected into the generator, not real customer behavior. "
    "Do not cite these numbers as business evidence."
)


def _provenance_sidecar_path(data_path: str | Path) -> Path:
    return Path(str(data_path) + ".provenance.json")


def write_provenance_sidecar(
    data_path: str | Path, *, source: str, data_provenance: str
) -> Path:
    """Record where an interaction file came from, next to the file itself.

    Training/evaluation scripts read this back so every model artifact and report can
    carry an honest ``data_provenance`` tag instead of silently mixing synthetic and
    real-source metrics.
    """

    sidecar = _provenance_sidecar_path(data_path)
    sidecar.write_text(
        json.dumps({"source": source, "data_provenance": data_provenance}, indent=2),
        encoding="utf-8",
    )
    return sidecar


def read_provenance_sidecar(data_path: str | Path) -> dict[str, str]:
    sidecar = _provenance_sidecar_path(data_path)
    if not sidecar.exists():
        return {"source": "unknown", "data_provenance": "unknown"}
    return json.loads(sidecar.read_text(encoding="utf-8"))

